# Generated by Django 2.2.4 on 2019-09-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='description',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
