# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-21 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_URL', models.TextField()),
                ('result', models.TextField()),
                ('respone', models.CharField(max_length=45)),
                ('user_id', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user_admin',
            name='user_type',
            field=models.CharField(default='user', max_length=45),
            preserve_default=False,
        ),
    ]
