# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-23 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='customer_name',
            new_name='user_name',
        ),
    ]
