# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-23 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20190923_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='feedback',
        ),
    ]
