# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-24 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20190923_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='read',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
