# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-24 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_user_admin_submitted_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_admin',
            name='about_me',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user_admin',
            name='catogray',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user_admin',
            name='experience',
            field=models.TextField(default=''),
        ),
    ]
