# Generated by Django 2.2.4 on 2019-09-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20190925_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='submitted_URL',
            field=models.TextField(),
        ),
    ]
