# Generated by Django 2.2.4 on 2019-09-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_ap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
