# Generated by Django 2.2.4 on 2019-09-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0002_auto_20190911_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Movies',
        ),
    ]
